# 参照1：https://xirikm.net/2020/313-1
# 参照2：https://juejin.im/post/6854573218779381773
name: Blog CI/CD  # 部署 Blog 到 GitHub Pages

on:
  push:
    branches:
      - hexo-src  # 当且仅当 master 分支发生 push 事件时才会触发本 workflow

env:
  TZ: Asia/Shanghai

jobs:
  # job 1
  blog-cicd:
    name: Hexo blog build & deploy  # 每次 commit 后自动部署 Blog 到 GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: 01.Checkout codes  # 检出代码
        uses: actions/checkout@v2

      - name: 02.Setup node  # 配置 node 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: 03.Cache node modules  # 设置 modules 缓存目录以免每次 workflow 都要重新下载，从而加快构建速度
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # 使用 package-lock.json 文件的 hash 值来标识缓存是否需要更新

      #- name: Set time zone  # 设置时区

      - name: 04.Install dependencies  # 安装依赖
        run: |
          npm install -g hexo-cli
          npm install

      - name: 05.Generate files  # 编译 markdown 文件
        run: |
          hexo clean
          hexo generate

      - name: 06.Deploy blog  # 部署博客
        env:
          # Github 仓库
          GH_REPO: github.com/sdokio/sdokio.github.io.git
        run: |
          cd ./public && git init && git add .
          git config user.name "sdokio"
          git config user.email "zdqdj@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.GH_ACCESS_TOKEN }}@$GH_REPO" master:master
